---
version: "3.4"

services:
  app:
    build: .
    ports:
      - "80:3000"
    volumes:
      - "./:/var/app:rw"
    restart: "always"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: "always"
